name: "Build Android release APK with EXPO"
branding:
  icon: "package"
  color: "green"
description: "Build Android release APK and upload as a github release match the created new tag"
author: "goblin-ihx"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
